-- Create syntax for TABLE 'tbl_order_item_000'
CREATE TABLE `tbl_order_item_000` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `orderKey` bigint(20) unsigned NOT NULL,
  `foodID` bigint(20) unsigned NOT NULL,
  `foodName` varchar(45) NOT NULL,
  `foodCode` varchar(50) NOT NULL DEFAULT '' COMMENT '菜品编号',
  `foodUnit` varchar(45) NOT NULL DEFAULT '' COMMENT '菜品规格',
  `foodUnitID` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '菜品规格ID',
  `foodCategoryID` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '菜品分类ID',
  `foodCategoryName` varchar(45) NOT NULL DEFAULT '' COMMENT '菜品分类名称',
  `customFoodCategoryName` varchar(80) NOT NULL DEFAULT '' COMMENT '平台菜品分类名称',
  `customFoodCategoryID` int(11) NOT NULL DEFAULT '0' COMMENT '平台菜品分类ID',
  `isSetFood` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否套餐',
  `SFMUnitCode` varchar(50) NOT NULL DEFAULT '' COMMENT '套餐Code',
  `isSFDetail` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否套餐明细',
  `foodSortIndex` tinyint(4) NOT NULL DEFAULT '0' COMMENT '套餐内排序',
  `isBatching` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否配料',
  `isGift` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否赠菜',
  `foodCount` decimal(10,2) NOT NULL COMMENT '已点数量',
  `remark` varchar(45) NOT NULL DEFAULT '' COMMENT '备注',
  `originPrice` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '原价',
  `originPoint` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '原价积分',
  `takeoutPackagingFee` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '打包费用',
  `isDiscount` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否折扣',
  `duePrice` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '售价（营销计算）',
  `duePoint` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '售价积分（营销计算）',
  `promoteTags` varchar(100) NOT NULL DEFAULT '' COMMENT '营销tags',
  `vipPrice` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '会员价',
  `vipPoint` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '会员积分',
  `batchNo` tinyint(4) NOT NULL DEFAULT '0' COMMENT '参加菜品批次号',
  `isAutoAdd` varchar(45) NOT NULL DEFAULT '0' COMMENT '是否自动加入',
  `itemDetail` varchar(5061) NOT NULL DEFAULT '',
  `action` tinyint(4) NOT NULL COMMENT '记录更新状态0insert1update2delete',
  `actionTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createTime` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `orderKey_` (`orderKey`)
) ENGINE=InnoDB AUTO_INCREMENT=252 DEFAULT CHARSET=utf8mb4;

-- Create syntax for TABLE 'tbl_order_master_000'
CREATE TABLE `tbl_order_master_000` (
  `orderID` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID，无业务含义',
  `orderKey` bigint(20) unsigned NOT NULL COMMENT '全局唯一orderKey',
  `parentOrderKey` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '拆单用维护父子关系orderKey',
  `shopOrderKey` varchar(50) NOT NULL DEFAULT '' COMMENT 'SAAS本地orderKey',
  `shopOrderFlowNo` varchar(50) NOT NULL DEFAULT '' COMMENT 'SAAS流水号（shopOrderKey后四位）',
  `paymentCheckCode` varchar(10) DEFAULT NULL COMMENT '支付检验码',
  `channelKey` varchar(10) NOT NULL DEFAULT '' COMMENT '外卖订单渠道',
  `channelOrderKey` varchar(50) NOT NULL DEFAULT '' COMMENT '外卖订单orderKey',
  `quoteID` varchar(50) NOT NULL DEFAULT '' COMMENT '云端购物车ID',
  `orderType` tinyint(3) unsigned NOT NULL COMMENT '订单类型',
  `orderSubType` mediumint(5) unsigned NOT NULL COMMENT '订单子类型',
  `orderStatus` tinyint(3) unsigned NOT NULL COMMENT '订单状态',
  `orderState` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '业务订单状态,与orderStatus有映射关系',
  `msgID` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'POS消息ID,消息用于云端与SAAS交互',
  `orderTime` bigint(20) NOT NULL COMMENT '订单时间，包含不限于预定时间、付款时间等,精确到分',
  `acceptTime` datetime DEFAULT NULL COMMENT '接单时间',
  `takeoutTime` datetime DEFAULT NULL COMMENT '外卖送出时间',
  `takeoutRemark` varchar(200) DEFAULT NULL COMMENT '外卖送出备注',
  `takeoutConfirmTime` datetime DEFAULT NULL COMMENT '下单时间',
  `takeoutConfirmRemark` varchar(200) NOT NULL DEFAULT '' COMMENT '下单备注',
  `groupID` bigint(20) unsigned NOT NULL COMMENT '集团ID',
  `groupName` varchar(60) NOT NULL DEFAULT '' COMMENT '集团ID',
  `shopID` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '店铺ID',
  `shopName` varchar(60) NOT NULL DEFAULT '' COMMENT '店铺名称',
  `shopAddress` varchar(200) NOT NULL DEFAULT '' COMMENT '店铺地址',
  `shopTel` varchar(50) NOT NULL DEFAULT '' COMMENT '店铺电话',
  `brandID` bigint(20) NOT NULL DEFAULT '0' COMMENT '品牌ID，同一集团下，可有多个品牌，一个品牌下，有多个店铺',
  `cardTypeID` varchar(45) NOT NULL DEFAULT '' COMMENT '卡类型ID，多卡',
  `cardID` varchar(150) NOT NULL DEFAULT '' COMMENT '卡ID',
  `cardNo` varchar(100) NOT NULL DEFAULT '' COMMENT '卡No.',
  `userID` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '用户ID',
  `userName` varchar(50) NOT NULL DEFAULT '' COMMENT '用户姓名',
  `userSex` tinyint(1) NOT NULL DEFAULT '0' COMMENT '顾客性别0女 1男',
  `userMobile` varchar(20) NOT NULL DEFAULT '' COMMENT '用户手机',
  `openID` varchar(50) NOT NULL DEFAULT '' COMMENT '微信openID',
  `offlinePaidAmount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '线下支付金额',
  `freeAmount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'SAAS减免金额',
  `foodAmount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '菜品原价',
  `foodCount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '食品数量',
  `promotionAmount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '优惠价',
  `serviceAmount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '服务费',
  `takeoutPackagingAmount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '外卖打包费',
  `isShopDelivery` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否商家自配送 0 否 1 是',
  `originTotalAmount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '原价',
  `originTotalPoint` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '原价积分',
  `dueTotalAmount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '应付金额',
  `dueTotalPoint` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '应付积分',
  `paidTotalAmount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '实付金额',
  `paidTotalPoint` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '实付积分',
  `refundTotalAmount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '退款总金额',
  `settleRefundAmount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '需结算退款总金额',
  `refundTotalPoint` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '退换总积分',
  `discountTotalAmount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '总折扣金额',
  `isAlreadyPaid` tinyint(4) NOT NULL DEFAULT '0' COMMENT ' 是否已支付 0 否 1 是',
  `thirdPartyAccount` varchar(100) NOT NULL DEFAULT '' COMMENT '第三方支付账号（结算用）',
  `thirdPartyCode` int(11) NOT NULL DEFAULT '0' COMMENT '第三方支付code（结算用）',
  `thirdPartyAmount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '第三方支付金额',
  `thirdPartyFreeAmount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '第三方支付优惠金额',
  `moneyBalance` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '会员卡余额支付金额',
  `pointBalance` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '会员卡积分抵扣金额',
  `payBeginTime` datetime DEFAULT NULL COMMENT '支付开始时间',
  `payEndTime` datetime DEFAULT NULL COMMENT '支付完成时间',
  `promotionType` varchar(20) NOT NULL DEFAULT '' COMMENT '促销类型',
  `appliedPromoteIDs` varchar(100) NOT NULL DEFAULT '' COMMENT '此次订单应用的促销规则ID',
  `orderRemark` varchar(250) NOT NULL DEFAULT '' COMMENT '订单备注',
  `invoiceTitle` varchar(100) NOT NULL DEFAULT '' COMMENT '发票抬头',
  `taxNo` varchar(100) NOT NULL DEFAULT '' COMMENT '发票抬头税号',
  `cancelRemark` varchar(150) NOT NULL DEFAULT '' COMMENT '取消订单原因',
  `cancelTime` datetime DEFAULT NULL COMMENT '取消订单时间',
  `clientType` varchar(50) NOT NULL DEFAULT '' COMMENT '客户类型',
  `deviceID` varchar(50) NOT NULL DEFAULT '' COMMENT '设备ID',
  `clientIP` varchar(30) NOT NULL DEFAULT '' COMMENT '客户端IP',
  `cityID` varchar(45) NOT NULL DEFAULT '' COMMENT '城市ID',
  `cityName` varchar(45) NOT NULL DEFAULT '' COMMENT '城市名称',
  `longitude` double(13,8) NOT NULL DEFAULT '0.00000000' COMMENT '地图经度',
  `latitude` double(13,8) NOT NULL DEFAULT '0.00000000' COMMENT '地图维度',
  `orderSettlementTotal` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '订单结算总金额',
  `settleID` varchar(50) NOT NULL DEFAULT '' COMMENT '此订单对应的结算ID',
  `isSettle` int(11) NOT NULL DEFAULT '0' COMMENT '结算状态，3位数字，分别表示备份,结算,反结算，每位数字由0,1,2,3四个状态，0初始,1发起,2成功,3失败，例如220为备份成功,结算成功',
  `settleBeginTime` datetime DEFAULT NULL COMMENT '结算发起时间',
  `settleEndTime` datetime DEFAULT NULL COMMENT '结算完成时间',
  `timeID` tinyint(4) NOT NULL DEFAULT '0' COMMENT '时段ID',
  `timeName` varchar(20) NOT NULL DEFAULT '' COMMENT '时段名称',
  `tableID` int(11) NOT NULL DEFAULT '0' COMMENT 'tableID',
  `tableName` varchar(20) NOT NULL DEFAULT '' COMMENT 'tableName',
  `dinners` int(11) NOT NULL DEFAULT '0' COMMENT '用餐人数',
  `takeoutAddress` varchar(100) NOT NULL DEFAULT '' COMMENT '外卖送餐地址',
  `takeoutDescribe` varchar(500) NOT NULL DEFAULT '' COMMENT '外卖描述',
  `operator` varchar(50) NOT NULL DEFAULT '' COMMENT '操作人',
  `action` tinyint(4) NOT NULL COMMENT '操作状态 0 insert 1 update 2delete',
  `actionTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间戳',
  `createTime` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`orderID`),
  UNIQUE KEY `orderKey_UNIQUE` (`orderKey`),
  KEY `idx_ordertime_shopid` (`shopID`,`orderTime`),
  KEY `idx_userID` (`userID`),
  KEY `idx_shopID` (`shopID`),
  KEY `idx_channelKey_channelOrderKey` (`channelKey`,`channelOrderKey`),
  KEY `idx_createTime` (`actionTime`,`createTime`,`msgID`,`groupID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=112 DEFAULT CHARSET=utf8mb4;

-- Create syntax for TABLE 'tbl_order_master_extra_000'
CREATE TABLE `tbl_order_master_extra_000` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `orderKey` bigint(20) NOT NULL,
  `extraInfo` varchar(5061) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `orderKey_UNIQUE` (`orderKey`)
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8mb4;

-- Create syntax for TABLE 'tbl_payment_detail_000'
CREATE TABLE `tbl_payment_detail_000` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `orderKey` bigint(20) unsigned NOT NULL,
  `paymentID` varchar(50) NOT NULL DEFAULT '' COMMENT '关联支付订单号',
  `balanceID` int(4) unsigned NOT NULL COMMENT '支付明细ID',
  `paymentSubjectCode` int(10) unsigned NOT NULL COMMENT '支付科目ID',
  `paymentSubjectName` varchar(45) NOT NULL COMMENT '支付科目名称',
  `payorAccount` varchar(45) NOT NULL DEFAULT '""' COMMENT '付款人账号',
  `payeeAccount` varchar(45) NOT NULL DEFAULT '""' COMMENT '收款人账号',
  `cardTypeID` varchar(100) NOT NULL DEFAULT '""',
  `dueAmount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '应付金额',
  `paidAmount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '实付金额',
  `paymentStatus` tinyint(4) NOT NULL DEFAULT '0' COMMENT '支付状态,20支付成功',
  `payBeginTime` datetime DEFAULT NULL COMMENT '支付提交时间',
  `payEndTime` datetime DEFAULT NULL COMMENT '支付时间',
  `scanType` varchar(10) NOT NULL DEFAULT '""' COMMENT '扫码方式 SCAN_QR 主扫 OR_SCAN 被扫',
  `transType` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否为退款 0:否,1:是',
  `refunded` tinyint(4) NOT NULL DEFAULT '0',
  `paymentRemark` varchar(100) NOT NULL DEFAULT '""' COMMENT '支付摘要:主扫\\被扫\\公众号',
  `settleID` varchar(20) NOT NULL DEFAULT '""' COMMENT '结算ID',
  `thirdPartyAccount` varchar(50) NOT NULL DEFAULT '""' COMMENT '结算冗余',
  `thirdPartyCode` int(11) NOT NULL DEFAULT '0' COMMENT '结算冗余',
  `settleBeginTime` datetime DEFAULT NULL,
  `settleEndTime` datetime DEFAULT NULL,
  `paymentVersion` timestamp NULL DEFAULT NULL,
  `operator` varchar(100) NOT NULL DEFAULT '""' COMMENT '操作人',
  `actionTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createTime` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `orderKey` (`orderKey`)
) ENGINE=InnoDB AUTO_INCREMENT=1091 DEFAULT CHARSET=utf8mb4;